name: baghera_tool
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7.2
  - pandas
  - bumpversion
  - snakemake
  - sphinx
  - sphinx_rtd_theme
  - pandas
  - mkl-service
  - numpy
  - htseq
  - gseapy
  - pymc3 >=3.6
