package:
  name: baghera
  version: 2.1.11

source:
  path: .

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

  entry_points:
      - baghera-tool = baghera_tool.cli:main

requirements:
  build:
    - nomkl
    - python==3.7.7
    - setuptools
    - argh==0.26.2
    - pandas==0.25.3
    - numpy==1.15.0
    - htseq==0.12.4
    - gseapy==0.9.19
    - pymc3==3.6

  run:
    - nomkl
    - python==3.7.7
    - setuptools
    - argh==0.26.2
    - pandas==0.25.3
    - numpy==1.15.0
    - htseq==0.12.4
    - gseapy==0.9.19
    - pymc3==3.6

test:
  commands:
    - baghera-tool --help | grep "regression"

about:
  home: https://github.com/stracquadaniolab/baghera
  summary: Bayesian Gene Heritability Analysis from GWAS summary statistics.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/stracquadaniolab/baghera
  doc_url: https://baghera.readthedocs.io/
  description: |
    The Bayesian Gene Heritability Analysis software (BAGHERA) estimates the contribution
    to the heritability of a trait/disease of all the SNPs in the genome (genome-wide heritability)
    and those nearby protein-coding genes (gene-level heritability).
    BAGHERA requires only summary statistics from a Genome-wide Association Study (GWAS),
    LD scores calculated from a population matching the ethnicity of the GWAS study
    and a gene annotation file in GTF format.
