version: 2.1

jobs:
  build_conda_package:
    parameters:
        python-version:
            type: string
            default: "3.7"
        numpy-version:
            type: string
            default: "1.15"

    docker:
      - image: continuumio/miniconda3

    context: ANACONDA_CLOUD_DEPLOY

    steps:
        - checkout

        - run:
            name: Configure Miniconda
            command: |
                conda config --set always_yes yes
                conda update -q conda
                conda config --add channels bioconda
                conda config --add channels conda-forge
                conda install conda-build
                conda install -c anaconda anaconda-client

        - run:
            name: Build package
            command: |
                conda build .conda_recipe -c bioconda -c conda-forge --python << parameters.python-version >> --numpy << parameters.numpy-version >>

        - run:
            name: Convert package
            command: |
                export TMP_PACKAGE_BUILD=`conda build .conda_recipe --output -c bioconda -c conda-forge --python << parameters.python-version >> \
                 --numpy << parameters.numpy-version >> | grep bz2`
                mkdir conda-bld/
                conda convert --platform osx-64 ${TMP_PACKAGE_BUILD} -o $HOME/conda-bld/
                conda convert --platform linux-32 ${TMP_PACKAGE_BUILD} -o conda-bld/
                conda convert --platform linux-64 ${TMP_PACKAGE_BUILD} -o conda-bld/

        - run:
            name: Upload package
            command: |
                anaconda -t ${UPLOAD_TOKEN} upload -u stracquadaniolab ${TMP_PACKAGE_BUILD}
                anaconda -t ${UPLOAD_TOKEN} upload -u stracquadaniolab conda-bld/*.bz2

workflows:

    build_baghera_py35:
        jobs:
            - build_conda_package
                python-version: 3.5
                numpy-version: 1.15

    build_baghera_py36:
        jobs:
            - build_conda_package
                python-version: 3.6
                numpy-version: 1.15

    build_baghera_py37:
        jobs:
            - build_conda_package
                python-version: 3.7
                numpy-version: 1.15

