name: base
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - nomkl
    - python
    - setuptools
    - argh
    - pandas==0.25.3
    - numpy==1.15.0
    - htseq
    - gseapy
    - pymc3==3.6
