name: base
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - nomkl
    - python
    - setuptools
    - argh
    - pandas<1.0
    - numpy==1.15
    - htseq
    - gseapy
    - pymc3==3.6
