name: base
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - nomkl
    - python
    - setuptools
    - argh
    - pandas
    - numpy
    - htseq
    - gseapy
    - pymc3 >=3.6
