name: "Release"

on:
    push:
        tags:
            - "*"

jobs:
    release:
        name: "Build Conda package"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [3.7]
                numpy: [1.15]
        steps:
            - uses: actions/checkout@v1
            - name: "Setup Conda"
              uses: s-weigand/setup-conda@v1
              with:
                  update-conda: true
                  python-version: ${{ matrix.python }}
                  conda-channels: anaconda, conda-forge, bioconda
            - name: "Install Conda development packages"
              run: |
                  conda install conda-build
                  conda install -c anaconda anaconda-client
            - name: "Build and upload package"
              run: |
                  mkdir conda-build
                  conda build . --no-build-id --numpy ${{ matrix.numpy }} --output-folder ./conda-build
                  conda convert -p all ./conda-build/**/baghera*.bz2 --output-dir ./conda-build
                  anaconda -t ${{ secrets.ANACONDA_API_TOKEN }} upload --force -u stracquadaniolab --no-progress ./conda-build/**/baghera*.bz2
            - name: "Release Docker image on GitHub Packages"
              uses: docker/build-push-action@v1
              with:
                  dockerfile: ./docker/Dockerfile
                  registry: docker.pkg.github.com
                  repository: ${{ github.repository }}/baghera
                  tags: latest
                  tag_with_ref: true
                  tag_with_sha: true
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: "Release Docker image on DockerHub"
              uses: docker/build-push-action@v1
              with:
                  dockerfile: ./docker/Dockerfile
                  repository: stracquadaniolab/baghera
                  tags: latest
                  tag_with_ref: true
                  tag_with_sha: true
                  username: ${{ secrets.DOCKERHUB_LOGIN }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
