name: "release"

on:
    push:
        branches:
        - '*'

jobs:
  release:
    name: "Build Conda package"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
        numpy: [1.15]
    steps:
      - uses: actions/checkout@v1
      - name: "Setup Conda"
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python }}
          conda-channels: anaconda, conda-forge, bioconda
      - name: "Install Conda development packages"
        run: |
            conda install conda-build
            conda install -c anaconda anaconda-client
      - name: "Build and upload package"
        run: |
            mkdir conda-build
            conda build . --no-build-id --numpy ${{ matrix.numpy }} --output-folder ./conda-build
            conda convert -p all ./conda-build/**/baghera*.bz2
            anaconda -t ${{ secrets.ANACONDA_API_TOKEN }} upload --force -u stracquadaniolab --no-progress ./conda-build/**/baghera*.bz2
